version: "2"
services:

    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      links:
        - prometheus
        - jaeger

    jaeger:
      image: jaegertracing/all-in-one:1.21
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411

    mrvl-dotnet-k8s-prototype-webapi:
      image: mrvl-dotnet-k8s-prototype-webapi
      ports:
        - "8080:8080"
      environment:
        - ASPNETCORE_URLS=http://+:8080
      links:
        - jaeger
        - mrvl-dotnet-k8s-prototype-backend

    mrvl-dotnet-k8s-prototype-backend:
      image: mrvl-dotnet-k8s-prototype-backend
      ports:
        - "8181:8181"
      environment:
        - ASPNETCORE_URLS=http://+:8181
      links:
        - jaeger

    prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - "./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      links:
        - mrvl-dotnet-k8s-prototype-webapi
        - mrvl-dotnet-k8s-prototype-backend
