version: "2"
services:

    jaeger:
      image: jaegertracing/all-in-one:1.21
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411

    mrvl-dotnet-k8s-prototype:
      image: mrvl-dotnet-k8s-prototype
      ports:
        - "8080:80"
      links:
        - jaeger

    # redis:
    #   image: redis:alpine
    #   ports:
    #     - "6379"
    #   environment:
    #     - SECRET_KEY=aabbcc
    #     - ENV_IS_SET

    # frontend:
    #   image: busybox
    #   #entrypoint: []
    #   command: ["/bin/busybox", "httpd", "-f", "-p", "8080"]
    #   working_dir: /
    #   environment:
    #     SECRET_KEY2: aabbcc
    #     ENV_IS_SET2:
    #   ports:
    #     - "8080"
    #   links:
    #     - redis:myredis
    #   labels:
    #     my.label: my_value

#$ docker run -d --name jaeger \
#  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
#  -p 5775:5775/udp \
#  -p 6831:6831/udp \
#  -p 6832:6832/udp \
#  -p 5778:5778 \
#  -p 16686:16686 \
#  -p 14268:14268 \
#  -p 14250:14250 \
#  -p 9411:9411 \
#  jaegertracing/all-in-one:1.21

#tmpfs: /run
#tmpfs:
#  - /run
#  - /tmp
#user: postgresql
#working_dir: /code
#domainname: foo.com
#hostname: foo
#ipc: host
#mac_address: 02:42:ac:11:65:43
#privileged: true
#read_only: true
#shm_size: 64M
#stdin_open: true
#tty: true
